### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by QQbbla** [Xiaolong-RRL/qwen2_5_vllm_fastapi#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/data1/liux/Qwen2.5/qwen2_5_vllm_fastapi/qwen2_5_vllm_fastapi_server.py", line 126, in chat
    results_iter = engine.generate(inputs=prompt_text,
TypeError: AsyncLLMEngine.generate() got an unexpected keyword argument 'inputs'

**Comment by QQbbla** [comment]
It looks like it's due to a change in the VLLM AsyncLLMEngine.generate() API from [v0.4.2](https://docs.vllm.ai/en/v0.4.2/dev/engine/async_llm_engine.html#vllm.AsyncLLMEngine.generate) to [v0.4.3](https://docs.vllm.ai/en/v0.4.3/dev/engine/async_llm_engine.html#vllm.AsyncLLMEngine.generate)

**Comment by sichehu** [comment]
> 这似乎是由于 VLLM AsyncLLMEngine.generate() API 从[v0.4.2](https://docs.vllm.ai/en/v0.4.2/dev/engine/async_llm_engine.html#vllm.AsyncLLMEngine.generate)更改为[v0.4.3造成的](https://docs.vllm.ai/en/v0.4.3/dev/engine/async_llm_engine.html#vllm.AsyncLLMEngine.generate)

请问作者使用的一些主要的库，比如vllm等的版本可以给一个说明嘛
